LONG_MEASURE = "LONG"
MIDDLE_MEASURE = "MIDDLE"
SHORT_MEASURE = "SHORT"

SCROLL_MEASURE_PERCENT = {LONG_MEASURE: 90,
                          MIDDLE_MEASURE: 50,
                          SHORT_MEASURE: 20}

UP_WAY = "UP"
DOWN_WAY = "DOWN"
LEFT_WAY = "LEFT"
RIGHT_WAY = "RIGHT"

DEFAULT_DURATION = 2200
